package heartbeat

import (
	"log"
	"os"
)

var (
	MOONSTREAM_HEARTBEAT_BUGOUT_ACCESS_TOKEN string
	MOONSTREAM_SEER_STATUS_JOURNAL         string
)

func init() {
	MOONSTREAM_ADMIN_ACCESS_TOKENHEARTBEAT_BUGOUT_ACCESS_TOKEN = os.Getenv("MOONSTREAM_HEARTBEAT_BUGOUT_ACCESS_TOKEN")
	if MOONSTREAM_HEARTBEAT_BUGOUT_ACCESS_TOKEN == "" {
		log.Println("Warning: MOONSTREAM_HEARTBEAT_BUGOUT_ACCESS_TOKEN not set")
	}

	MOONSTREAM_SEER_STATUS_JOURNAL = os.Getenv("MOONSTREAM_SEER_STATUS_JOURNAL")
	if MOONSTREAM_SEER_STATUS_JOURNAL == "" {
		log.Println("Warning: MOONSTREAM_SEER_STATUS_JOURNAL not set")
	}
}
