"""initial indexes

Revision ID: c01f2789f996
Revises: 
Create Date: 2024-03-07 17:27:48.321201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01f2789f996'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abi_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=256), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('abi_selector', sa.VARCHAR(length=256), nullable=False),
    sa.Column('chain', sa.VARCHAR(length=256), nullable=False),
    sa.Column('abi_name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('status', sa.VARCHAR(length=256), nullable=False),
    sa.Column('historical_crawl_status', sa.VARCHAR(length=256), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('moonworm_task_pickedup', sa.Boolean(), nullable=False),
    sa.Column('abi', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abi_jobs'))
    )
    op.create_index(op.f('ix_abi_jobs_abi_name'), 'abi_jobs', ['abi_name'], unique=False)
    op.create_index(op.f('ix_abi_jobs_abi_selector'), 'abi_jobs', ['abi_selector'], unique=False)
    op.create_index(op.f('ix_abi_jobs_address'), 'abi_jobs', ['address'], unique=False)
    op.create_index(op.f('ix_abi_jobs_chain'), 'abi_jobs', ['chain'], unique=False)
    op.create_index(op.f('ix_abi_jobs_customer_id'), 'abi_jobs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_abi_jobs_historical_crawl_status'), 'abi_jobs', ['historical_crawl_status'], unique=False)
    op.create_index(op.f('ix_abi_jobs_status'), 'abi_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_abi_jobs_user_id'), 'abi_jobs', ['user_id'], unique=False)
    op.create_table('ethereum_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(), nullable=False),
    sa.Column('parent_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ethereum_index'))
    )
    op.create_index(op.f('ix_ethereum_index_block_hash'), 'ethereum_index', ['block_hash'], unique=False)
    op.create_index(op.f('ix_ethereum_index_block_number'), 'ethereum_index', ['block_number'], unique=False)
    op.create_index(op.f('ix_ethereum_index_block_timestamp'), 'ethereum_index', ['block_timestamp'], unique=False)
    op.create_table('ethereum_log_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(), nullable=False),
    sa.Column('transaction_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('selector', sa.VARCHAR(length=256), nullable=False),
    sa.Column('topic1', sa.VARCHAR(length=256), nullable=False),
    sa.Column('topic2', sa.VARCHAR(length=256), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ethereum_log_index'))
    )
    op.create_index(op.f('ix_ethereum_log_index_block_hash'), 'ethereum_log_index', ['block_hash'], unique=False)
    op.create_index(op.f('ix_ethereum_log_index_block_number'), 'ethereum_log_index', ['block_number'], unique=False)
    op.create_index(op.f('ix_ethereum_log_index_block_timestamp'), 'ethereum_log_index', ['block_timestamp'], unique=False)
    op.create_index(op.f('ix_ethereum_log_index_log_index'), 'ethereum_log_index', ['log_index'], unique=False)
    op.create_index(op.f('ix_ethereum_log_index_selector'), 'ethereum_log_index', ['selector'], unique=False)
    op.create_index(op.f('ix_ethereum_log_index_topic1'), 'ethereum_log_index', ['topic1'], unique=False)
    op.create_index(op.f('ix_ethereum_log_index_topic2'), 'ethereum_log_index', ['topic2'], unique=False)
    op.create_index(op.f('ix_ethereum_log_index_transaction_hash'), 'ethereum_log_index', ['transaction_hash'], unique=False)
    op.create_table('ethereum_transaction_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(), nullable=False),
    sa.Column('transaction_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('transaction_index', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ethereum_transaction_index'))
    )
    op.create_index(op.f('ix_ethereum_transaction_index_block_hash'), 'ethereum_transaction_index', ['block_hash'], unique=False)
    op.create_index(op.f('ix_ethereum_transaction_index_block_number'), 'ethereum_transaction_index', ['block_number'], unique=False)
    op.create_index(op.f('ix_ethereum_transaction_index_block_timestamp'), 'ethereum_transaction_index', ['block_timestamp'], unique=False)
    op.create_index(op.f('ix_ethereum_transaction_index_transaction_hash'), 'ethereum_transaction_index', ['transaction_hash'], unique=False)
    op.create_index(op.f('ix_ethereum_transaction_index_transaction_index'), 'ethereum_transaction_index', ['transaction_index'], unique=False)
    op.create_table('polygon_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(), nullable=False),
    sa.Column('parent_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polygon_index'))
    )
    op.create_index(op.f('ix_polygon_index_block_hash'), 'polygon_index', ['block_hash'], unique=False)
    op.create_index(op.f('ix_polygon_index_block_number'), 'polygon_index', ['block_number'], unique=False)
    op.create_index(op.f('ix_polygon_index_block_timestamp'), 'polygon_index', ['block_timestamp'], unique=False)
    op.create_index(op.f('ix_polygon_index_parent_hash'), 'polygon_index', ['parent_hash'], unique=False)
    op.create_table('polygon_log_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(), nullable=False),
    sa.Column('transaction_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('selector', sa.VARCHAR(length=256), nullable=False),
    sa.Column('topic1', sa.VARCHAR(length=256), nullable=False),
    sa.Column('topic2', sa.VARCHAR(length=256), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polygon_log_index'))
    )
    op.create_index(op.f('ix_polygon_log_index_block_hash'), 'polygon_log_index', ['block_hash'], unique=False)
    op.create_index(op.f('ix_polygon_log_index_block_number'), 'polygon_log_index', ['block_number'], unique=False)
    op.create_index(op.f('ix_polygon_log_index_block_timestamp'), 'polygon_log_index', ['block_timestamp'], unique=False)
    op.create_index(op.f('ix_polygon_log_index_selector'), 'polygon_log_index', ['selector'], unique=False)
    op.create_index(op.f('ix_polygon_log_index_topic1'), 'polygon_log_index', ['topic1'], unique=False)
    op.create_index(op.f('ix_polygon_log_index_topic2'), 'polygon_log_index', ['topic2'], unique=False)
    op.create_index(op.f('ix_polygon_log_index_transaction_hash'), 'polygon_log_index', ['transaction_hash'], unique=False)
    op.create_table('polygon_transaction_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(), nullable=False),
    sa.Column('transaction_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('transaction_index', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polygon_transaction_index'))
    )
    op.create_index(op.f('ix_polygon_transaction_index_block_hash'), 'polygon_transaction_index', ['block_hash'], unique=False)
    op.create_index(op.f('ix_polygon_transaction_index_block_number'), 'polygon_transaction_index', ['block_number'], unique=False)
    op.create_index(op.f('ix_polygon_transaction_index_block_timestamp'), 'polygon_transaction_index', ['block_timestamp'], unique=False)
    op.create_index(op.f('ix_polygon_transaction_index_transaction_hash'), 'polygon_transaction_index', ['transaction_hash'], unique=False)
    op.create_index(op.f('ix_polygon_transaction_index_transaction_index'), 'polygon_transaction_index', ['transaction_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_polygon_transaction_index_transaction_index'), table_name='polygon_transaction_index')
    op.drop_index(op.f('ix_polygon_transaction_index_transaction_hash'), table_name='polygon_transaction_index')
    op.drop_index(op.f('ix_polygon_transaction_index_block_timestamp'), table_name='polygon_transaction_index')
    op.drop_index(op.f('ix_polygon_transaction_index_block_number'), table_name='polygon_transaction_index')
    op.drop_index(op.f('ix_polygon_transaction_index_block_hash'), table_name='polygon_transaction_index')
    op.drop_table('polygon_transaction_index')
    op.drop_index(op.f('ix_polygon_log_index_transaction_hash'), table_name='polygon_log_index')
    op.drop_index(op.f('ix_polygon_log_index_topic2'), table_name='polygon_log_index')
    op.drop_index(op.f('ix_polygon_log_index_topic1'), table_name='polygon_log_index')
    op.drop_index(op.f('ix_polygon_log_index_selector'), table_name='polygon_log_index')
    op.drop_index(op.f('ix_polygon_log_index_block_timestamp'), table_name='polygon_log_index')
    op.drop_index(op.f('ix_polygon_log_index_block_number'), table_name='polygon_log_index')
    op.drop_index(op.f('ix_polygon_log_index_block_hash'), table_name='polygon_log_index')
    op.drop_table('polygon_log_index')
    op.drop_index(op.f('ix_polygon_index_parent_hash'), table_name='polygon_index')
    op.drop_index(op.f('ix_polygon_index_block_timestamp'), table_name='polygon_index')
    op.drop_index(op.f('ix_polygon_index_block_number'), table_name='polygon_index')
    op.drop_index(op.f('ix_polygon_index_block_hash'), table_name='polygon_index')
    op.drop_table('polygon_index')
    op.drop_index(op.f('ix_ethereum_transaction_index_transaction_index'), table_name='ethereum_transaction_index')
    op.drop_index(op.f('ix_ethereum_transaction_index_transaction_hash'), table_name='ethereum_transaction_index')
    op.drop_index(op.f('ix_ethereum_transaction_index_block_timestamp'), table_name='ethereum_transaction_index')
    op.drop_index(op.f('ix_ethereum_transaction_index_block_number'), table_name='ethereum_transaction_index')
    op.drop_index(op.f('ix_ethereum_transaction_index_block_hash'), table_name='ethereum_transaction_index')
    op.drop_table('ethereum_transaction_index')
    op.drop_index(op.f('ix_ethereum_log_index_transaction_hash'), table_name='ethereum_log_index')
    op.drop_index(op.f('ix_ethereum_log_index_topic2'), table_name='ethereum_log_index')
    op.drop_index(op.f('ix_ethereum_log_index_topic1'), table_name='ethereum_log_index')
    op.drop_index(op.f('ix_ethereum_log_index_selector'), table_name='ethereum_log_index')
    op.drop_index(op.f('ix_ethereum_log_index_log_index'), table_name='ethereum_log_index')
    op.drop_index(op.f('ix_ethereum_log_index_block_timestamp'), table_name='ethereum_log_index')
    op.drop_index(op.f('ix_ethereum_log_index_block_number'), table_name='ethereum_log_index')
    op.drop_index(op.f('ix_ethereum_log_index_block_hash'), table_name='ethereum_log_index')
    op.drop_table('ethereum_log_index')
    op.drop_index(op.f('ix_ethereum_index_block_timestamp'), table_name='ethereum_index')
    op.drop_index(op.f('ix_ethereum_index_block_number'), table_name='ethereum_index')
    op.drop_index(op.f('ix_ethereum_index_block_hash'), table_name='ethereum_index')
    op.drop_table('ethereum_index')
    op.drop_index(op.f('ix_abi_jobs_user_id'), table_name='abi_jobs')
    op.drop_index(op.f('ix_abi_jobs_status'), table_name='abi_jobs')
    op.drop_index(op.f('ix_abi_jobs_historical_crawl_status'), table_name='abi_jobs')
    op.drop_index(op.f('ix_abi_jobs_customer_id'), table_name='abi_jobs')
    op.drop_index(op.f('ix_abi_jobs_chain'), table_name='abi_jobs')
    op.drop_index(op.f('ix_abi_jobs_address'), table_name='abi_jobs')
    op.drop_index(op.f('ix_abi_jobs_abi_selector'), table_name='abi_jobs')
    op.drop_index(op.f('ix_abi_jobs_abi_name'), table_name='abi_jobs')
    op.drop_table('abi_jobs')
    # ### end Alembic commands ###
