"""base, optimism, and degen indexes

Revision ID: af69b3528849
Revises: 6807bdf6f417
Create Date: 2024-10-01 17:50:35.627106

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af69b3528849"
down_revision: Union[str, None] = "6807bdf6f417"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base_blocks",
        sa.Column("l1_block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_hash", sa.VARCHAR(length=256), nullable=False),
        sa.Column("block_timestamp", sa.BigInteger(), nullable=False),
        sa.Column("parent_hash", sa.VARCHAR(length=256), nullable=False),
        sa.Column("row_id", sa.BigInteger(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("transactions_indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("logs_indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "indexed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', statement_timestamp())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("block_number", name=op.f("pk_base_blocks")),
    )
    op.create_index(
        op.f("ix_base_blocks_block_number"),
        "base_blocks",
        ["block_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_base_blocks_block_timestamp"),
        "base_blocks",
        ["block_timestamp"],
        unique=False,
    )
    op.create_table(
        "base_reorgs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_hash", sa.VARCHAR(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_base_reorgs")),
    )
    op.create_index(
        op.f("ix_base_reorgs_block_hash"), "base_reorgs", ["block_hash"], unique=False
    )
    op.create_index(
        op.f("ix_base_reorgs_block_number"),
        "base_reorgs",
        ["block_number"],
        unique=False,
    )
    op.create_table(
        "base_sepolia_blocks",
        sa.Column("l1_block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_hash", sa.VARCHAR(length=256), nullable=False),
        sa.Column("block_timestamp", sa.BigInteger(), nullable=False),
        sa.Column("parent_hash", sa.VARCHAR(length=256), nullable=False),
        sa.Column("row_id", sa.BigInteger(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("transactions_indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("logs_indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "indexed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', statement_timestamp())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("block_number", name=op.f("pk_base_sepolia_blocks")),
    )
    op.create_index(
        op.f("ix_base_sepolia_blocks_block_number"),
        "base_sepolia_blocks",
        ["block_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_base_sepolia_blocks_block_timestamp"),
        "base_sepolia_blocks",
        ["block_timestamp"],
        unique=False,
    )
    op.create_table(
        "base_sepolia_reorgs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_hash", sa.VARCHAR(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_base_sepolia_reorgs")),
    )
    op.create_index(
        op.f("ix_base_sepolia_reorgs_block_hash"),
        "base_sepolia_reorgs",
        ["block_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_base_sepolia_reorgs_block_number"),
        "base_sepolia_reorgs",
        ["block_number"],
        unique=False,
    )
    op.create_table(
        "degen_blocks",
        sa.Column("l1_block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_hash", sa.VARCHAR(length=256), nullable=False),
        sa.Column("block_timestamp", sa.BigInteger(), nullable=False),
        sa.Column("parent_hash", sa.VARCHAR(length=256), nullable=False),
        sa.Column("row_id", sa.BigInteger(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("transactions_indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("logs_indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "indexed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', statement_timestamp())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("block_number", name=op.f("pk_degen_blocks")),
    )
    op.create_index(
        op.f("ix_degen_blocks_block_number"),
        "degen_blocks",
        ["block_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_degen_blocks_block_timestamp"),
        "degen_blocks",
        ["block_timestamp"],
        unique=False,
    )
    op.create_table(
        "degen_reorgs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_hash", sa.VARCHAR(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_degen_reorgs")),
    )
    op.create_index(
        op.f("ix_degen_reorgs_block_hash"), "degen_reorgs", ["block_hash"], unique=False
    )
    op.create_index(
        op.f("ix_degen_reorgs_block_number"),
        "degen_reorgs",
        ["block_number"],
        unique=False,
    )
    op.create_table(
        "optimism_blocks",
        sa.Column("l1_block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_hash", sa.VARCHAR(length=256), nullable=False),
        sa.Column("block_timestamp", sa.BigInteger(), nullable=False),
        sa.Column("parent_hash", sa.VARCHAR(length=256), nullable=False),
        sa.Column("row_id", sa.BigInteger(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("transactions_indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("logs_indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "indexed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', statement_timestamp())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("block_number", name=op.f("pk_optimism_blocks")),
    )
    op.create_index(
        op.f("ix_optimism_blocks_block_number"),
        "optimism_blocks",
        ["block_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_optimism_blocks_block_timestamp"),
        "optimism_blocks",
        ["block_timestamp"],
        unique=False,
    )
    op.create_table(
        "optimism_reorgs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_hash", sa.VARCHAR(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_optimism_reorgs")),
    )
    op.create_index(
        op.f("ix_optimism_reorgs_block_hash"),
        "optimism_reorgs",
        ["block_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_optimism_reorgs_block_number"),
        "optimism_reorgs",
        ["block_number"],
        unique=False,
    )
    op.create_table(
        "optimism_sepolia_blocks",
        sa.Column("l1_block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_hash", sa.VARCHAR(length=256), nullable=False),
        sa.Column("block_timestamp", sa.BigInteger(), nullable=False),
        sa.Column("parent_hash", sa.VARCHAR(length=256), nullable=False),
        sa.Column("row_id", sa.BigInteger(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("transactions_indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("logs_indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "indexed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', statement_timestamp())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "block_number", name=op.f("pk_optimism_sepolia_blocks")
        ),
    )
    op.create_index(
        op.f("ix_optimism_sepolia_blocks_block_number"),
        "optimism_sepolia_blocks",
        ["block_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_optimism_sepolia_blocks_block_timestamp"),
        "optimism_sepolia_blocks",
        ["block_timestamp"],
        unique=False,
    )
    op.create_table(
        "optimism_sepolia_reorgs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("block_hash", sa.VARCHAR(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_optimism_sepolia_reorgs")),
    )
    op.create_index(
        op.f("ix_optimism_sepolia_reorgs_block_hash"),
        "optimism_sepolia_reorgs",
        ["block_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_optimism_sepolia_reorgs_block_number"),
        "optimism_sepolia_reorgs",
        ["block_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_optimism_sepolia_reorgs_block_number"),
        table_name="optimism_sepolia_reorgs",
    )
    op.drop_index(
        op.f("ix_optimism_sepolia_reorgs_block_hash"),
        table_name="optimism_sepolia_reorgs",
    )
    op.drop_table("optimism_sepolia_reorgs")
    op.drop_index(
        op.f("ix_optimism_sepolia_blocks_block_timestamp"),
        table_name="optimism_sepolia_blocks",
    )
    op.drop_index(
        op.f("ix_optimism_sepolia_blocks_block_number"),
        table_name="optimism_sepolia_blocks",
    )
    op.drop_table("optimism_sepolia_blocks")
    op.drop_index(op.f("ix_optimism_reorgs_block_number"), table_name="optimism_reorgs")
    op.drop_index(op.f("ix_optimism_reorgs_block_hash"), table_name="optimism_reorgs")
    op.drop_table("optimism_reorgs")
    op.drop_index(
        op.f("ix_optimism_blocks_block_timestamp"), table_name="optimism_blocks"
    )
    op.drop_index(op.f("ix_optimism_blocks_block_number"), table_name="optimism_blocks")
    op.drop_table("optimism_blocks")
    op.drop_index(op.f("ix_degen_reorgs_block_number"), table_name="degen_reorgs")
    op.drop_index(op.f("ix_degen_reorgs_block_hash"), table_name="degen_reorgs")
    op.drop_table("degen_reorgs")
    op.drop_index(op.f("ix_degen_blocks_block_timestamp"), table_name="degen_blocks")
    op.drop_index(op.f("ix_degen_blocks_block_number"), table_name="degen_blocks")
    op.drop_table("degen_blocks")
    op.drop_index(
        op.f("ix_base_sepolia_reorgs_block_number"), table_name="base_sepolia_reorgs"
    )
    op.drop_index(
        op.f("ix_base_sepolia_reorgs_block_hash"), table_name="base_sepolia_reorgs"
    )
    op.drop_table("base_sepolia_reorgs")
    op.drop_index(
        op.f("ix_base_sepolia_blocks_block_timestamp"), table_name="base_sepolia_blocks"
    )
    op.drop_index(
        op.f("ix_base_sepolia_blocks_block_number"), table_name="base_sepolia_blocks"
    )
    op.drop_table("base_sepolia_blocks")
    op.drop_index(op.f("ix_base_reorgs_block_number"), table_name="base_reorgs")
    op.drop_index(op.f("ix_base_reorgs_block_hash"), table_name="base_reorgs")
    op.drop_table("base_reorgs")
    op.drop_index(op.f("ix_base_blocks_block_timestamp"), table_name="base_blocks")
    op.drop_index(op.f("ix_base_blocks_block_number"), table_name="base_blocks")
    op.drop_table("base_blocks")
    # ### end Alembic commands ###
