"""base optimism degen

Revision ID: 89e4ebedf339
Revises: 1d53afc1eff4
Create Date: 2024-10-01 17:55:01.824115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89e4ebedf339'
down_revision: Union[str, None] = '1d53afc1eff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_sepolia_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=256), nullable=False),
    sa.Column('transaction_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('caller_address', sa.LargeBinary(), nullable=True),
    sa.Column('origin_address', sa.LargeBinary(), nullable=True),
    sa.Column('address', sa.LargeBinary(), nullable=False),
    sa.Column('label_name', sa.Text(), nullable=True),
    sa.Column('label_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('label_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_base_sepolia_labels')),
    sa.UniqueConstraint('id', name=op.f('uq_base_sepolia_labels_id'))
    )
    op.create_index('ix_base_sepolia_labels_addr_block_num', 'base_sepolia_labels', ['address', 'block_number'], unique=False)
    op.create_index('ix_base_sepolia_labels_addr_block_ts', 'base_sepolia_labels', ['address', 'block_timestamp'], unique=False)
    op.create_index(op.f('ix_base_sepolia_labels_address'), 'base_sepolia_labels', ['address'], unique=False)
    op.create_index(op.f('ix_base_sepolia_labels_block_number'), 'base_sepolia_labels', ['block_number'], unique=False)
    op.create_index(op.f('ix_base_sepolia_labels_caller_address'), 'base_sepolia_labels', ['caller_address'], unique=False)
    op.create_index(op.f('ix_base_sepolia_labels_label'), 'base_sepolia_labels', ['label'], unique=False)
    op.create_index(op.f('ix_base_sepolia_labels_label_name'), 'base_sepolia_labels', ['label_name'], unique=False)
    op.create_index(op.f('ix_base_sepolia_labels_label_type'), 'base_sepolia_labels', ['label_type'], unique=False)
    op.create_index(op.f('ix_base_sepolia_labels_origin_address'), 'base_sepolia_labels', ['origin_address'], unique=False)
    op.create_index(op.f('ix_base_sepolia_labels_transaction_hash'), 'base_sepolia_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_base_sepolia_labels_tx_hash_log_idx_evt', 'base_sepolia_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_base_sepolia_labels_tx_hash_log_idx_evt_raw', 'base_sepolia_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer-raw' and label_type='event'"))
    op.create_index('uk_base_sepolia_labels_tx_hash_tx_call', 'base_sepolia_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.create_index('uk_base_sepolia_labels_tx_hash_tx_call_raw', 'base_sepolia_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer-raw' and label_type='tx_call'"))
    op.create_table('degen_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=256), nullable=False),
    sa.Column('transaction_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('caller_address', sa.LargeBinary(), nullable=True),
    sa.Column('origin_address', sa.LargeBinary(), nullable=True),
    sa.Column('address', sa.LargeBinary(), nullable=False),
    sa.Column('label_name', sa.Text(), nullable=True),
    sa.Column('label_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('label_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_degen_labels')),
    sa.UniqueConstraint('id', name=op.f('uq_degen_labels_id'))
    )
    op.create_index('ix_degen_labels_addr_block_num', 'degen_labels', ['address', 'block_number'], unique=False)
    op.create_index('ix_degen_labels_addr_block_ts', 'degen_labels', ['address', 'block_timestamp'], unique=False)
    op.create_index(op.f('ix_degen_labels_address'), 'degen_labels', ['address'], unique=False)
    op.create_index(op.f('ix_degen_labels_block_number'), 'degen_labels', ['block_number'], unique=False)
    op.create_index(op.f('ix_degen_labels_caller_address'), 'degen_labels', ['caller_address'], unique=False)
    op.create_index(op.f('ix_degen_labels_label'), 'degen_labels', ['label'], unique=False)
    op.create_index(op.f('ix_degen_labels_label_name'), 'degen_labels', ['label_name'], unique=False)
    op.create_index(op.f('ix_degen_labels_label_type'), 'degen_labels', ['label_type'], unique=False)
    op.create_index(op.f('ix_degen_labels_origin_address'), 'degen_labels', ['origin_address'], unique=False)
    op.create_index(op.f('ix_degen_labels_transaction_hash'), 'degen_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_degen_labels_tx_hash_log_idx_evt', 'degen_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_degen_labels_tx_hash_log_idx_evt_raw', 'degen_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer-raw' and label_type='event'"))
    op.create_index('uk_degen_labels_tx_hash_tx_call', 'degen_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.create_index('uk_degen_labels_tx_hash_tx_call_raw', 'degen_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer-raw' and label_type='tx_call'"))
    op.create_table('optimism_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=256), nullable=False),
    sa.Column('transaction_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('caller_address', sa.LargeBinary(), nullable=True),
    sa.Column('origin_address', sa.LargeBinary(), nullable=True),
    sa.Column('address', sa.LargeBinary(), nullable=False),
    sa.Column('label_name', sa.Text(), nullable=True),
    sa.Column('label_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('label_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimism_labels')),
    sa.UniqueConstraint('id', name=op.f('uq_optimism_labels_id'))
    )
    op.create_index('ix_optimism_labels_addr_block_num', 'optimism_labels', ['address', 'block_number'], unique=False)
    op.create_index('ix_optimism_labels_addr_block_ts', 'optimism_labels', ['address', 'block_timestamp'], unique=False)
    op.create_index(op.f('ix_optimism_labels_address'), 'optimism_labels', ['address'], unique=False)
    op.create_index(op.f('ix_optimism_labels_block_number'), 'optimism_labels', ['block_number'], unique=False)
    op.create_index(op.f('ix_optimism_labels_caller_address'), 'optimism_labels', ['caller_address'], unique=False)
    op.create_index(op.f('ix_optimism_labels_label'), 'optimism_labels', ['label'], unique=False)
    op.create_index(op.f('ix_optimism_labels_label_name'), 'optimism_labels', ['label_name'], unique=False)
    op.create_index(op.f('ix_optimism_labels_label_type'), 'optimism_labels', ['label_type'], unique=False)
    op.create_index(op.f('ix_optimism_labels_origin_address'), 'optimism_labels', ['origin_address'], unique=False)
    op.create_index(op.f('ix_optimism_labels_transaction_hash'), 'optimism_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_optimism_labels_tx_hash_log_idx_evt', 'optimism_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_optimism_labels_tx_hash_log_idx_evt_raw', 'optimism_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer-raw' and label_type='event'"))
    op.create_index('uk_optimism_labels_tx_hash_tx_call', 'optimism_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.create_index('uk_optimism_labels_tx_hash_tx_call_raw', 'optimism_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer-raw' and label_type='tx_call'"))
    op.create_table('optimism_sepolia_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=256), nullable=False),
    sa.Column('transaction_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('block_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('caller_address', sa.LargeBinary(), nullable=True),
    sa.Column('origin_address', sa.LargeBinary(), nullable=True),
    sa.Column('address', sa.LargeBinary(), nullable=False),
    sa.Column('label_name', sa.Text(), nullable=True),
    sa.Column('label_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('label_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimism_sepolia_labels')),
    sa.UniqueConstraint('id', name=op.f('uq_optimism_sepolia_labels_id'))
    )
    op.create_index('ix_optimism_sepolia_labels_addr_block_num', 'optimism_sepolia_labels', ['address', 'block_number'], unique=False)
    op.create_index('ix_optimism_sepolia_labels_addr_block_ts', 'optimism_sepolia_labels', ['address', 'block_timestamp'], unique=False)
    op.create_index(op.f('ix_optimism_sepolia_labels_address'), 'optimism_sepolia_labels', ['address'], unique=False)
    op.create_index(op.f('ix_optimism_sepolia_labels_block_number'), 'optimism_sepolia_labels', ['block_number'], unique=False)
    op.create_index(op.f('ix_optimism_sepolia_labels_caller_address'), 'optimism_sepolia_labels', ['caller_address'], unique=False)
    op.create_index(op.f('ix_optimism_sepolia_labels_label'), 'optimism_sepolia_labels', ['label'], unique=False)
    op.create_index(op.f('ix_optimism_sepolia_labels_label_name'), 'optimism_sepolia_labels', ['label_name'], unique=False)
    op.create_index(op.f('ix_optimism_sepolia_labels_label_type'), 'optimism_sepolia_labels', ['label_type'], unique=False)
    op.create_index(op.f('ix_optimism_sepolia_labels_origin_address'), 'optimism_sepolia_labels', ['origin_address'], unique=False)
    op.create_index(op.f('ix_optimism_sepolia_labels_transaction_hash'), 'optimism_sepolia_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_optimism_sepolia_labels_tx_hash_log_idx_evt', 'optimism_sepolia_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_optimism_sepolia_labels_tx_hash_log_idx_evt_raw', 'optimism_sepolia_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer-raw' and label_type='event'"))
    op.create_index('uk_optimism_sepolia_labels_tx_hash_tx_call', 'optimism_sepolia_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.create_index('uk_optimism_sepolia_labels_tx_hash_tx_call_raw', 'optimism_sepolia_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer-raw' and label_type='tx_call'"))
    op.alter_column('amoy_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_amoy_labels_transaction_hash_log_index_event', table_name='amoy_labels')
    op.drop_index('uk_amoy_labels_transaction_hash_tx_call', table_name='amoy_labels')
    op.create_index('uk_amoy_labels_tx_hash_log_idx_evt', 'amoy_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_amoy_labels_tx_hash_tx_call', 'amoy_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('arbitrum_nova_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_arbitrum_nova_labels_transaction_hash_log_index_event', table_name='arbitrum_nova_labels')
    op.drop_index('uk_arbitrum_nova_labels_transaction_hash_tx_call', table_name='arbitrum_nova_labels')
    op.create_index('uk_arbitrum_nova_labels_tx_hash_log_idx_evt', 'arbitrum_nova_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_arbitrum_nova_labels_tx_hash_tx_call', 'arbitrum_nova_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('arbitrum_one_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_arbitrum_one_labels_transaction_hash_log_index_event', table_name='arbitrum_one_labels')
    op.drop_index('uk_arbitrum_one_labels_transaction_hash_tx_call', table_name='arbitrum_one_labels')
    op.create_index('uk_arbitrum_one_labels_tx_hash_log_idx_evt', 'arbitrum_one_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_arbitrum_one_labels_tx_hash_tx_call', 'arbitrum_one_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('arbitrum_sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_arbitrum_sepolia_labels_transaction_hash_log_index_event', table_name='arbitrum_sepolia_labels')
    op.drop_index('uk_arbitrum_sepolia_labels_transaction_hash_tx_call', table_name='arbitrum_sepolia_labels')
    op.create_index('uk_arbitrum_sepolia_labels_tx_hash_log_idx_evt', 'arbitrum_sepolia_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_arbitrum_sepolia_labels_tx_hash_tx_call', 'arbitrum_sepolia_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('avalanche_fuji_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_avalanche_fuji_labels_transaction_hash_log_index_event', table_name='avalanche_fuji_labels')
    op.drop_index('uk_avalanche_fuji_labels_transaction_hash_tx_call', table_name='avalanche_fuji_labels')
    op.create_index('uk_avalanche_fuji_labels_tx_hash_log_idx_evt', 'avalanche_fuji_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_avalanche_fuji_labels_tx_hash_tx_call', 'avalanche_fuji_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('avalanche_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_avalanche_labels_transaction_hash_log_index_event', table_name='avalanche_labels')
    op.drop_index('uk_avalanche_labels_transaction_hash_tx_call', table_name='avalanche_labels')
    op.create_index('uk_avalanche_labels_tx_hash_log_idx_evt', 'avalanche_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_avalanche_labels_tx_hash_tx_call', 'avalanche_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.create_unique_constraint(op.f('uq_b3_labels_id'), 'b3_labels', ['id'])
    op.create_unique_constraint(op.f('uq_b3_sepolia_labels_id'), 'b3_sepolia_labels', ['id'])
    op.alter_column('base_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_base_labels_transaction_hash_log_index_event', table_name='base_labels')
    op.drop_index('uk_base_labels_transaction_hash_tx_call', table_name='base_labels')
    op.create_index('uk_base_labels_tx_hash_log_idx_evt', 'base_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_base_labels_tx_hash_tx_call', 'base_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('blast_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_blast_labels_transaction_hash_log_index_event', table_name='blast_labels')
    op.drop_index('uk_blast_labels_transaction_hash_tx_call', table_name='blast_labels')
    op.create_index('uk_blast_labels_tx_hash_log_idx_evt', 'blast_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_blast_labels_tx_hash_tx_call', 'blast_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('blast_sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_blast_sepolia_labels_transaction_hash_log_index_event', table_name='blast_sepolia_labels')
    op.drop_index('uk_blast_sepolia_labels_transaction_hash_tx_call', table_name='blast_sepolia_labels')
    op.create_index('uk_blast_sepolia_labels_tx_hash_log_idx_evt', 'blast_sepolia_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_blast_sepolia_labels_tx_hash_tx_call', 'blast_sepolia_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('ethereum_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_ethereum_labels_transaction_hash_log_index_event', table_name='ethereum_labels')
    op.drop_index('uk_ethereum_labels_transaction_hash_tx_call', table_name='ethereum_labels')
    op.create_index('uk_ethereum_labels_tx_hash_log_idx_evt', 'ethereum_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_ethereum_labels_tx_hash_tx_call', 'ethereum_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('game7_orbit_arbitrum_sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_game7_orbit_arbitrum_sepolia_labels_id'), 'game7_orbit_arbitrum_sepolia_labels', ['id'])
    op.create_unique_constraint(op.f('uq_game7_testnet_labels_id'), 'game7_testnet_labels', ['id'])
    op.create_unique_constraint(op.f('uq_imx_zkevm_labels_id'), 'imx_zkevm_labels', ['id'])
    op.create_unique_constraint(op.f('uq_imx_zkevm_sepolia_labels_id'), 'imx_zkevm_sepolia_labels', ['id'])
    op.alter_column('mantle_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_mantle_labels_id'), 'mantle_labels', ['id'])
    op.alter_column('mantle_sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_mantle_sepolia_labels_id'), 'mantle_sepolia_labels', ['id'])
    op.alter_column('mumbai_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_mumbai_labels_transaction_hash_log_index_event', table_name='mumbai_labels')
    op.drop_index('uk_mumbai_labels_transaction_hash_tx_call', table_name='mumbai_labels')
    op.create_index('uk_mumbai_labels_tx_hash_log_idx_evt', 'mumbai_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_mumbai_labels_tx_hash_tx_call', 'mumbai_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('polygon_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_polygon_labels_transaction_hash_log_index_event', table_name='polygon_labels')
    op.drop_index('uk_polygon_labels_transaction_hash_tx_call', table_name='polygon_labels')
    op.create_index('uk_polygon_labels_tx_hash_log_idx_evt', 'polygon_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_polygon_labels_tx_hash_tx_call', 'polygon_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('proofofplay_apex_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_proofofplay_apex_labels_transaction_hash_log_index_event', table_name='proofofplay_apex_labels')
    op.drop_index('uk_proofofplay_apex_labels_transaction_hash_tx_call', table_name='proofofplay_apex_labels')
    op.create_index('uk_proofofplay_apex_labels_tx_hash_log_idx_evt', 'proofofplay_apex_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_proofofplay_apex_labels_tx_hash_tx_call', 'proofofplay_apex_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_sepolia_labels_transaction_hash_log_index_event', table_name='sepolia_labels')
    op.drop_index('uk_sepolia_labels_transaction_hash_tx_call', table_name='sepolia_labels')
    op.create_index('uk_sepolia_labels_tx_hash_log_idx_evt', 'sepolia_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_sepolia_labels_tx_hash_tx_call', 'sepolia_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('starknet_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_starknet_labels_transaction_hash_log_index_event', table_name='starknet_labels')
    op.drop_index('uk_starknet_labels_transaction_hash_tx_call', table_name='starknet_labels')
    op.create_index('uk_starknet_labels_tx_hash_log_idx_evt', 'starknet_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_starknet_labels_tx_hash_tx_call', 'starknet_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('starknet_sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_starknet_sepolia_labels_transaction_hash_log_index_event', table_name='starknet_sepolia_labels')
    op.drop_index('uk_starknet_sepolia_labels_transaction_hash_tx_call', table_name='starknet_sepolia_labels')
    op.create_index('uk_starknet_sepolia_labels_tx_hash_log_idx_evt', 'starknet_sepolia_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_starknet_sepolia_labels_tx_hash_tx_call', 'starknet_sepolia_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('xai_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_xai_labels_transaction_hash_log_index_event', table_name='xai_labels')
    op.drop_index('uk_xai_labels_transaction_hash_tx_call', table_name='xai_labels')
    op.create_index('uk_xai_labels_tx_hash_log_idx_evt', 'xai_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_xai_labels_tx_hash_tx_call', 'xai_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('xai_sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_xai_sepolia_labels_transaction_hash_log_index_event', table_name='xai_sepolia_labels')
    op.drop_index('uk_xai_sepolia_labels_transaction_hash_tx_call', table_name='xai_sepolia_labels')
    op.create_index('uk_xai_sepolia_labels_tx_hash_log_idx_evt', 'xai_sepolia_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_xai_sepolia_labels_tx_hash_tx_call', 'xai_sepolia_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('xdai_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_xdai_labels_transaction_hash_log_index_event', table_name='xdai_labels')
    op.drop_index('uk_xdai_labels_transaction_hash_tx_call', table_name='xdai_labels')
    op.create_index('uk_xdai_labels_tx_hash_log_idx_evt', 'xdai_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_xdai_labels_tx_hash_tx_call', 'xdai_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('zksync_era_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_zksync_era_labels_transaction_hash_log_index_event', table_name='zksync_era_labels')
    op.drop_index('uk_zksync_era_labels_transaction_hash_tx_call', table_name='zksync_era_labels')
    op.create_index('uk_zksync_era_labels_tx_hash_log_idx_evt', 'zksync_era_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_zksync_era_labels_tx_hash_tx_call', 'zksync_era_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.alter_column('zksync_era_sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_index('uk_zksync_era_sepolia_labels_transaction_hash_log_index_event', table_name='zksync_era_sepolia_labels')
    op.drop_index('uk_zksync_era_sepolia_labels_transaction_hash_tx_call', table_name='zksync_era_sepolia_labels')
    op.create_index('uk_zksync_era_sepolia_labels_tx_hash_log_idx_evt', 'zksync_era_sepolia_labels', ['transaction_hash', 'log_index'], unique=True, postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_zksync_era_sepolia_labels_tx_hash_tx_call', 'zksync_era_sepolia_labels', ['transaction_hash'], unique=True, postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uk_zksync_era_sepolia_labels_tx_hash_tx_call', table_name='zksync_era_sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_zksync_era_sepolia_labels_tx_hash_log_idx_evt', table_name='zksync_era_sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_zksync_era_sepolia_labels_transaction_hash_tx_call', 'zksync_era_sepolia_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_zksync_era_sepolia_labels_transaction_hash_log_index_event', 'zksync_era_sepolia_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('zksync_era_sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_zksync_era_labels_tx_hash_tx_call', table_name='zksync_era_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_zksync_era_labels_tx_hash_log_idx_evt', table_name='zksync_era_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_zksync_era_labels_transaction_hash_tx_call', 'zksync_era_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_zksync_era_labels_transaction_hash_log_index_event', 'zksync_era_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('zksync_era_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_xdai_labels_tx_hash_tx_call', table_name='xdai_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_xdai_labels_tx_hash_log_idx_evt', table_name='xdai_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_xdai_labels_transaction_hash_tx_call', 'xdai_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_xdai_labels_transaction_hash_log_index_event', 'xdai_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('xdai_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_xai_sepolia_labels_tx_hash_tx_call', table_name='xai_sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_xai_sepolia_labels_tx_hash_log_idx_evt', table_name='xai_sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_xai_sepolia_labels_transaction_hash_tx_call', 'xai_sepolia_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_xai_sepolia_labels_transaction_hash_log_index_event', 'xai_sepolia_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('xai_sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_xai_labels_tx_hash_tx_call', table_name='xai_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_xai_labels_tx_hash_log_idx_evt', table_name='xai_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_xai_labels_transaction_hash_tx_call', 'xai_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_xai_labels_transaction_hash_log_index_event', 'xai_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('xai_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_starknet_sepolia_labels_tx_hash_tx_call', table_name='starknet_sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_starknet_sepolia_labels_tx_hash_log_idx_evt', table_name='starknet_sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_starknet_sepolia_labels_transaction_hash_tx_call', 'starknet_sepolia_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_starknet_sepolia_labels_transaction_hash_log_index_event', 'starknet_sepolia_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('starknet_sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_starknet_labels_tx_hash_tx_call', table_name='starknet_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_starknet_labels_tx_hash_log_idx_evt', table_name='starknet_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_starknet_labels_transaction_hash_tx_call', 'starknet_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_starknet_labels_transaction_hash_log_index_event', 'starknet_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('starknet_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_sepolia_labels_tx_hash_tx_call', table_name='sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_sepolia_labels_tx_hash_log_idx_evt', table_name='sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_sepolia_labels_transaction_hash_tx_call', 'sepolia_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_sepolia_labels_transaction_hash_log_index_event', 'sepolia_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_proofofplay_apex_labels_tx_hash_tx_call', table_name='proofofplay_apex_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_proofofplay_apex_labels_tx_hash_log_idx_evt', table_name='proofofplay_apex_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_proofofplay_apex_labels_transaction_hash_tx_call', 'proofofplay_apex_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_proofofplay_apex_labels_transaction_hash_log_index_event', 'proofofplay_apex_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('proofofplay_apex_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_polygon_labels_tx_hash_tx_call', table_name='polygon_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_polygon_labels_tx_hash_log_idx_evt', table_name='polygon_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_polygon_labels_transaction_hash_tx_call', 'polygon_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_polygon_labels_transaction_hash_log_index_event', 'polygon_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('polygon_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_mumbai_labels_tx_hash_tx_call', table_name='mumbai_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_mumbai_labels_tx_hash_log_idx_evt', table_name='mumbai_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_mumbai_labels_transaction_hash_tx_call', 'mumbai_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_mumbai_labels_transaction_hash_log_index_event', 'mumbai_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('mumbai_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_constraint(op.f('uq_mantle_sepolia_labels_id'), 'mantle_sepolia_labels', type_='unique')
    op.alter_column('mantle_sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_constraint(op.f('uq_mantle_labels_id'), 'mantle_labels', type_='unique')
    op.alter_column('mantle_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_constraint(op.f('uq_imx_zkevm_sepolia_labels_id'), 'imx_zkevm_sepolia_labels', type_='unique')
    op.drop_constraint(op.f('uq_imx_zkevm_labels_id'), 'imx_zkevm_labels', type_='unique')
    op.drop_constraint(op.f('uq_game7_testnet_labels_id'), 'game7_testnet_labels', type_='unique')
    op.drop_constraint(op.f('uq_game7_orbit_arbitrum_sepolia_labels_id'), 'game7_orbit_arbitrum_sepolia_labels', type_='unique')
    op.alter_column('game7_orbit_arbitrum_sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_ethereum_labels_tx_hash_tx_call', table_name='ethereum_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_ethereum_labels_tx_hash_log_idx_evt', table_name='ethereum_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_ethereum_labels_transaction_hash_tx_call', 'ethereum_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_ethereum_labels_transaction_hash_log_index_event', 'ethereum_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('ethereum_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_blast_sepolia_labels_tx_hash_tx_call', table_name='blast_sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_blast_sepolia_labels_tx_hash_log_idx_evt', table_name='blast_sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_blast_sepolia_labels_transaction_hash_tx_call', 'blast_sepolia_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_blast_sepolia_labels_transaction_hash_log_index_event', 'blast_sepolia_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('blast_sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_blast_labels_tx_hash_tx_call', table_name='blast_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_blast_labels_tx_hash_log_idx_evt', table_name='blast_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_blast_labels_transaction_hash_tx_call', 'blast_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_blast_labels_transaction_hash_log_index_event', 'blast_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('blast_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_base_labels_tx_hash_tx_call', table_name='base_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_base_labels_tx_hash_log_idx_evt', table_name='base_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_base_labels_transaction_hash_tx_call', 'base_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_base_labels_transaction_hash_log_index_event', 'base_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('base_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_constraint(op.f('uq_b3_sepolia_labels_id'), 'b3_sepolia_labels', type_='unique')
    op.drop_constraint(op.f('uq_b3_labels_id'), 'b3_labels', type_='unique')
    op.drop_index('uk_avalanche_labels_tx_hash_tx_call', table_name='avalanche_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_avalanche_labels_tx_hash_log_idx_evt', table_name='avalanche_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_avalanche_labels_transaction_hash_tx_call', 'avalanche_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_avalanche_labels_transaction_hash_log_index_event', 'avalanche_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('avalanche_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_avalanche_fuji_labels_tx_hash_tx_call', table_name='avalanche_fuji_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_avalanche_fuji_labels_tx_hash_log_idx_evt', table_name='avalanche_fuji_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_avalanche_fuji_labels_transaction_hash_tx_call', 'avalanche_fuji_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_avalanche_fuji_labels_transaction_hash_log_index_event', 'avalanche_fuji_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('avalanche_fuji_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_arbitrum_sepolia_labels_tx_hash_tx_call', table_name='arbitrum_sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_arbitrum_sepolia_labels_tx_hash_log_idx_evt', table_name='arbitrum_sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_arbitrum_sepolia_labels_transaction_hash_tx_call', 'arbitrum_sepolia_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_arbitrum_sepolia_labels_transaction_hash_log_index_event', 'arbitrum_sepolia_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('arbitrum_sepolia_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_arbitrum_one_labels_tx_hash_tx_call', table_name='arbitrum_one_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_arbitrum_one_labels_tx_hash_log_idx_evt', table_name='arbitrum_one_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_arbitrum_one_labels_transaction_hash_tx_call', 'arbitrum_one_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_arbitrum_one_labels_transaction_hash_log_index_event', 'arbitrum_one_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('arbitrum_one_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_arbitrum_nova_labels_tx_hash_tx_call', table_name='arbitrum_nova_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_arbitrum_nova_labels_tx_hash_log_idx_evt', table_name='arbitrum_nova_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_arbitrum_nova_labels_transaction_hash_tx_call', 'arbitrum_nova_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_arbitrum_nova_labels_transaction_hash_log_index_event', 'arbitrum_nova_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('arbitrum_nova_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_amoy_labels_tx_hash_tx_call', table_name='amoy_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_amoy_labels_tx_hash_log_idx_evt', table_name='amoy_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.create_index('uk_amoy_labels_transaction_hash_tx_call', 'amoy_labels', ['transaction_hash'], unique=False)
    op.create_index('uk_amoy_labels_transaction_hash_log_index_event', 'amoy_labels', ['transaction_hash', 'log_index'], unique=False)
    op.alter_column('amoy_labels', 'address',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_index('uk_optimism_sepolia_labels_tx_hash_tx_call_raw', table_name='optimism_sepolia_labels', postgresql_where=sa.text("label='seer-raw' and label_type='tx_call'"))
    op.drop_index('uk_optimism_sepolia_labels_tx_hash_tx_call', table_name='optimism_sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_optimism_sepolia_labels_tx_hash_log_idx_evt_raw', table_name='optimism_sepolia_labels', postgresql_where=sa.text("label='seer-raw' and label_type='event'"))
    op.drop_index('uk_optimism_sepolia_labels_tx_hash_log_idx_evt', table_name='optimism_sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.drop_index(op.f('ix_optimism_sepolia_labels_transaction_hash'), table_name='optimism_sepolia_labels')
    op.drop_index(op.f('ix_optimism_sepolia_labels_origin_address'), table_name='optimism_sepolia_labels')
    op.drop_index(op.f('ix_optimism_sepolia_labels_label_type'), table_name='optimism_sepolia_labels')
    op.drop_index(op.f('ix_optimism_sepolia_labels_label_name'), table_name='optimism_sepolia_labels')
    op.drop_index(op.f('ix_optimism_sepolia_labels_label'), table_name='optimism_sepolia_labels')
    op.drop_index(op.f('ix_optimism_sepolia_labels_caller_address'), table_name='optimism_sepolia_labels')
    op.drop_index(op.f('ix_optimism_sepolia_labels_block_number'), table_name='optimism_sepolia_labels')
    op.drop_index(op.f('ix_optimism_sepolia_labels_address'), table_name='optimism_sepolia_labels')
    op.drop_index('ix_optimism_sepolia_labels_addr_block_ts', table_name='optimism_sepolia_labels')
    op.drop_index('ix_optimism_sepolia_labels_addr_block_num', table_name='optimism_sepolia_labels')
    op.drop_table('optimism_sepolia_labels')
    op.drop_index('uk_optimism_labels_tx_hash_tx_call_raw', table_name='optimism_labels', postgresql_where=sa.text("label='seer-raw' and label_type='tx_call'"))
    op.drop_index('uk_optimism_labels_tx_hash_tx_call', table_name='optimism_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_optimism_labels_tx_hash_log_idx_evt_raw', table_name='optimism_labels', postgresql_where=sa.text("label='seer-raw' and label_type='event'"))
    op.drop_index('uk_optimism_labels_tx_hash_log_idx_evt', table_name='optimism_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.drop_index(op.f('ix_optimism_labels_transaction_hash'), table_name='optimism_labels')
    op.drop_index(op.f('ix_optimism_labels_origin_address'), table_name='optimism_labels')
    op.drop_index(op.f('ix_optimism_labels_label_type'), table_name='optimism_labels')
    op.drop_index(op.f('ix_optimism_labels_label_name'), table_name='optimism_labels')
    op.drop_index(op.f('ix_optimism_labels_label'), table_name='optimism_labels')
    op.drop_index(op.f('ix_optimism_labels_caller_address'), table_name='optimism_labels')
    op.drop_index(op.f('ix_optimism_labels_block_number'), table_name='optimism_labels')
    op.drop_index(op.f('ix_optimism_labels_address'), table_name='optimism_labels')
    op.drop_index('ix_optimism_labels_addr_block_ts', table_name='optimism_labels')
    op.drop_index('ix_optimism_labels_addr_block_num', table_name='optimism_labels')
    op.drop_table('optimism_labels')
    op.drop_index('uk_degen_labels_tx_hash_tx_call_raw', table_name='degen_labels', postgresql_where=sa.text("label='seer-raw' and label_type='tx_call'"))
    op.drop_index('uk_degen_labels_tx_hash_tx_call', table_name='degen_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_degen_labels_tx_hash_log_idx_evt_raw', table_name='degen_labels', postgresql_where=sa.text("label='seer-raw' and label_type='event'"))
    op.drop_index('uk_degen_labels_tx_hash_log_idx_evt', table_name='degen_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.drop_index(op.f('ix_degen_labels_transaction_hash'), table_name='degen_labels')
    op.drop_index(op.f('ix_degen_labels_origin_address'), table_name='degen_labels')
    op.drop_index(op.f('ix_degen_labels_label_type'), table_name='degen_labels')
    op.drop_index(op.f('ix_degen_labels_label_name'), table_name='degen_labels')
    op.drop_index(op.f('ix_degen_labels_label'), table_name='degen_labels')
    op.drop_index(op.f('ix_degen_labels_caller_address'), table_name='degen_labels')
    op.drop_index(op.f('ix_degen_labels_block_number'), table_name='degen_labels')
    op.drop_index(op.f('ix_degen_labels_address'), table_name='degen_labels')
    op.drop_index('ix_degen_labels_addr_block_ts', table_name='degen_labels')
    op.drop_index('ix_degen_labels_addr_block_num', table_name='degen_labels')
    op.drop_table('degen_labels')
    op.drop_index('uk_base_sepolia_labels_tx_hash_tx_call_raw', table_name='base_sepolia_labels', postgresql_where=sa.text("label='seer-raw' and label_type='tx_call'"))
    op.drop_index('uk_base_sepolia_labels_tx_hash_tx_call', table_name='base_sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='tx_call'"))
    op.drop_index('uk_base_sepolia_labels_tx_hash_log_idx_evt_raw', table_name='base_sepolia_labels', postgresql_where=sa.text("label='seer-raw' and label_type='event'"))
    op.drop_index('uk_base_sepolia_labels_tx_hash_log_idx_evt', table_name='base_sepolia_labels', postgresql_where=sa.text("label='seer' and label_type='event'"))
    op.drop_index(op.f('ix_base_sepolia_labels_transaction_hash'), table_name='base_sepolia_labels')
    op.drop_index(op.f('ix_base_sepolia_labels_origin_address'), table_name='base_sepolia_labels')
    op.drop_index(op.f('ix_base_sepolia_labels_label_type'), table_name='base_sepolia_labels')
    op.drop_index(op.f('ix_base_sepolia_labels_label_name'), table_name='base_sepolia_labels')
    op.drop_index(op.f('ix_base_sepolia_labels_label'), table_name='base_sepolia_labels')
    op.drop_index(op.f('ix_base_sepolia_labels_caller_address'), table_name='base_sepolia_labels')
    op.drop_index(op.f('ix_base_sepolia_labels_block_number'), table_name='base_sepolia_labels')
    op.drop_index(op.f('ix_base_sepolia_labels_address'), table_name='base_sepolia_labels')
    op.drop_index('ix_base_sepolia_labels_addr_block_ts', table_name='base_sepolia_labels')
    op.drop_index('ix_base_sepolia_labels_addr_block_num', table_name='base_sepolia_labels')
    op.drop_table('base_sepolia_labels')
    # ### end Alembic commands ###
